### ISSUE TITLE
Visualizing blast output

### ISSUE THREAD

**Issue by apn83** [nspies/genomeview#10]
Hi,
This is a great tool. Is it possible to visualize blast hits over reference file ? 
-> blast outfmt 15 -- blast_output.sam
-> samtools -Sb blast_output.bam
Can this bam file with hits be viewed ? Is this feasible ? 
Thanks,
AP

**Comment by nspies** [comment]
I don’t see why not! You’ll just need to make sure there’s also a bam index file. 
		
		

		
	




On Thu, Sep 20, 2018 at 1:12 PM -0400, "gitarunprasanna83" <notifications@github.com> wrote:












Hi,

This is a great tool. Is it possible to visualize blast hits over reference file ?

-> blast outfmt 15 -- blast_output.sam

-> samtools -Sb blast_output.bam

Can this bam file with hits be viewed ? Is this feasible ?

Thanks,

AP
