### ISSUE TITLE
how to plot a fusion event using genomeview

### ISSUE THREAD

**Issue by xiucz** [nspies/genomeview#14]
Hi, 
I have found this part [Modular design¶ ](https://nbviewer.jupyter.org/github/nspies/genomeview/blob/master/examples/examples.ipynb) are quite useful, but how to plot a fusion event with gene1 on the left and gene2 on the right?

I can see the fusion event using IGV easily, but not so expediently. 
Thank you
Xiucz

**Comment by nspies** [comment]
Have you tried https://github.com/nspies/svviz2?
