### ISSUE TITLE
Question on example data

### ISSUE THREAD

**Issue by mtinti** [nspies/genomeview#17]
Hi,
can you please tell how to create the chr1_200mb.refseq.sorted.bed file in the example/data directory?
thanks for your time,
Michele

**Comment by nspies-celsiustx** [comment]
That's a great question! I should have included the scripts used to generate the example data in the repo, but unfortunately I don't have them anymore. I expect something like this should work, but please let me know if you hit any snags:

- use the ucsc table browser to download refseq genes in bed format

That's a great question! I should have included the scripts used to generate the example data in the repo, but unfortunately I don't have them anymore. I expect something like this should work, but please let me know if you hit any snags:

- use the [ucsc table browser](http://genome.ucsc.edu/cgi-bin/hgTables?command=start) to download refseq genes in bed format
- use bedtools to ensure the bed file is sorted
- use [bgzip](http://www.htslib.org/doc/bgzip.html) to create a block gzipped file
- use [tabix](http://www.htslib.org/doc/tabix.html) to index the bgzipped file using the bed preset

**Comment by nspies** [comment]
That's a great question! I should have included the scripts used to generate the example data in the repo, but unfortunately I don't have them anymore. I expect something like this should work, but please let me know if you hit any snags:

- use the ucsc table browser to download refseq genes in bed format

That's a great question! I should have included the scripts used to generate the example data in the repo, but unfortunately I don't have them anymore. I expect something like this should work, but please let me know if you hit any snags:

- use the [ucsc table browser](http://genome.ucsc.edu/cgi-bin/hgTables?command=start) to download refseq genes in bed format
- use bedtools to ensure the bed file is sorted
- use [bgzip](http://www.htslib.org/doc/bgzip.html) to create a block gzipped file
- use [tabix](http://www.htslib.org/doc/tabix.html) to index the bgzipped file using the bed preset
