### ISSUE TITLE
Bed file format related issue

### ISSUE THREAD

**Issue by ghost** [nspies/genomeview#19]
First of all, thanks to @nspies  for making this tool. 

I mainly process WES data. To visualize the bam file, I usually add an annotation track of genes along with the bam tracks. And the gene annotation resource usually comes from RefGene instead of Ensemble and UCSC.

Therefore, I would like to add one BedTrack using a bed format annotation file from RefGene. However, I did not find any specific requirements of the bed file in the genomeview's doc(like which column should contain what type of info).

Fortunately, in the site-packages relevant dir, the bedtrack.py records how genomeview parses plain bed files. As I understand, it converts every row into a Transcript Class(self-defined within genomeview). Here is the code:

`def tx_from_bedfields(bedfields):
    """
    create a Transcript instance from bed fields (ie the result of
    bed_line.strip().split())
    """

    chrom, start, end = bedfields[0:3]
    name = coding_start = coding_end = exons = color = None
    strand = "+"

    if len(bedfields) >= 4:
        name = bedfields[3]
    if len(bedfields) >= 6:
        strand = bedfields[5]
    if len(bedfields) >= 7:
        coding_start = bedfields[6]
        coding_end = bedfields[7]
    if len(bedfields) >= 12 and int(bedfields[9]) > 0:
        exon_lengths = [int(x) for x in bedfields[10].split(",") if x]
        exon_starts = [int(x) for x in bedfields[11].split(",") if x]

        exons = [(int(start)+exon_start, int(start)+exon_start+exon_length)
                 for exon_start, exon_length in zip(exon_starts, exon_lengths)]

        # print("^^^", bedfields, exon_starts, exon_lengths, exons)

    return Transcript(chrom, start, end, strand, name, coding_start, coding_end, exons, color)`

If I understand this part correctly, here are the basic format requirements for the bed file:

> The first three columns are chr, start, end

> The fourth column should be the name

> It does not provide field content of the fifth column.

> The sixth column should be strand

> The seventh column should be cds_start

> The eighth column should be cds_end

> It does not provide field content of the ninth column.

> The tenth column should be the total number of exons

> The eleventh column should be the coordinates of starting site for every exon

> The last column should be the coordinates of the ending site for every exon.

The rules above are consistent with the format of the example bed file in official's tutorial doc: chr1_200mb.refseq.sorted.bed.gz. So I followed the requirements to prepare my own refGene annotation bed to add a BedTrack. 

However, when I tried to add one bedtrack with proper format, I receive a ValueError message like this:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/bamvis/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/anaconda3/envs/bamvis/lib/python3.6/site-packages/genomeview/genomeview.py in _repr_svg_(self)
     51 
     52     def _repr_svg_(self):
---> 53         return "\n".join(self.render())
     54 
     55 class ViewRow:

~/anaconda3/envs/bamvis/lib/python3.6/site-packages/genomeview/genomeview.py in render(self)
     37 
     38     def render(self):
---> 39         self.layout()
     40 
     41         total_height = sum(element.height+self.between_views for element in self.elements) + self.margin_y*2

~/anaconda3/envs/bamvis/lib/python3.6/site-packages/genomeview/genomeview.py in layout(self)
     34         self.view_width = self.width - self.margin_x*2
     35         for element in self.elements:
---> 36             element.layout(self.view_width)
     37 
     38     def render(self):

~/anaconda3/envs/bamvis/lib/python3.6/site-packages/genomeview/genomeview.py in layout(self, width)
    128         self.height = 0
    129         for track in self.tracks:
--> 130             track.layout(self.scale)
    131             self.height += track.height + self.margin_y
    132 

~/anaconda3/envs/bamvis/lib/python3.6/site-packages/genomeview/intervaltrack.py in layout(self, scale)
     74         self.intervals_to_rows = {}
     75 
---> 76         for interval in self.intervals:
     77             self.layout_interval(interval)
     78 

~/anaconda3/envs/bamvis/lib/python3.6/site-packages/genomeview/bedtrack.py in __iter__(self)
    156     def __iter__(self):
    157         c = 0
--> 158         for i, tx in enumerate(self.fetch()):
    159             c += 1
    160             id_ = tx.name if tx.name else "feature"

~/anaconda3/envs/bamvis/lib/python3.6/site-packages/genomeview/bedtrack.py in fetch(self)
    150         start, end = self.scale.start, self.scale.end
    151 
--> 152         for locus in fetch(self.bed_path, chrom, start, end):
    153             if not self.include_locus_fn or self.include_locus_fn(locus):
    154                 yield locus

~/anaconda3/envs/bamvis/lib/python3.6/site-packages/genomeview/bedtrack.py in fetch(path, chrom, start, end)
     74 
     75     try:
---> 76         yield from fetch_from_plainbed(path, chrom, start, end)
     77         return
     78     except:

~/anaconda3/envs/bamvis/lib/python3.6/site-packages/genomeview/bedtrack.py in fetch_from_plainbed(path, chrom, start, end)
    113         cur_start, cur_end = fields[1:3]
    114         if int(cur_end) < start or int(cur_start) > end: continue
--> 115         yield tx_from_bedfields(fields)
    116 
    117     if not found_chrom:

~/anaconda3/envs/bamvis/lib/python3.6/site-packages/genomeview/bedtrack.py in tx_from_bedfields(bedfields)
     58         # print("^^^", bedfields, exon_starts, exon_lengths, exons)
     59 
---> 60     return Transcript(chrom, start, end, strand, name, coding_start, coding_end, exons, color)
     61 
     62 def fetch(path, chrom, start, end):

~/anaconda3/envs/bamvis/lib/python3.6/site-packages/genomeview/bedtrack.py in __init__(self, chrom, start, end, strand, name, coding_start, coding_end, exons, color)
     20         self.coding_start = None
     21         if coding_start is not None:
---> 22             self.coding_start = int(coding_start)
     23 
     24         self.coding_end = None

ValueError: invalid literal for int() with base 10: '+'`

I suppose it's because there is a plus symbol in the cds_start column? So I go out and check the file with awk and other UNIX-based tools and make sure there are not any special characters in the 7th column of my plain bed file.

Therefore, I'm stuck here. I dunno what's wrong with the bed. Could @nspies pls consider taking some time look at this issue and add up some instruction regarding bed file in the official doc of the genomeview. 

Much obliged!

**Comment by Yangyxt1991** [comment]
I seem to resolve this bug by removing all the blanks in the field content.
Since the

**Comment by ghost** [comment]
I seem to resolve this bug by removing all the blanks in the field content.
Since the bedtrack.py parse each line by using ".strip().split()"
Every blank will be treated as a delimiter.
