### ISSUE TITLE
Failed to show the bed track, it's all blank

### ISSUE THREAD

**Issue by ghost** [nspies/genomeview#20]
First of all, thanks @nspies for making this tool.

I used a plain bed file, which has consistent format with the example bed file: chr1_200mb.refseq.sorted.bed.gz, to add gene annotation track. 

Here is the screenshot of my bed file:
![image](https://user-images.githubusercontent.com/41467037/75103884-6756f500-563c-11ea-91eb-32ea51469493.png)

Though the code runs smoothly, I failed to get a bed track as introduced and expected:
![image](https://user-images.githubusercontent.com/41467037/75103876-3e366480-563c-11ea-9dbb-071786ba5655.png)
Instead, I get this:
![image](https://user-images.githubusercontent.com/41467037/75103891-86558700-563c-11ea-8d4d-3d5525ed6f58.png)

I'm pretty sure the region I inspected is covered with exons so there should be some gene annotation lines in the BedTrack. However, it's blank now. 

Much obliged if @nspies can take a look at this at your convenience!

**Comment by nspies-celsiustx** [comment]
Can you share the precise code you're using to show the tracks? I'm not sure I'll be a whole lot of help here -- it's been a couple of years since I've used genomeview substantially -- but am happy to take a look.

**Comment by ghost** [comment]
> Can you share the precise code you're using to show the tracks? I'm not sure I'll be a whole lot of help here -- it's been a couple of years since I've used genomeview substantially -- but am happy to take a look.

Thanks, @nspies for the reply. I'm right in need of this. I used two methods to visualize.

Here is the code for the first convenience method:
==========================================================================
```
trackpaths = { 'refgene':'<path_to_my_gene_annotation_bed_file>', 
                           'pro_bam':'<path_to_patient_bamfile>', 
                           'mo_bam':'<path_to_patient's_mom_bamfile>', 
                           'fa_bam':'<path_to_patient's_dad_bamfile>' }

genomeview.visualize_data( trackpaths, 
                                                  reference_path='/Users/UCSC/ucsc.hg19.fasta', 
                                                  chrom='chr5', start=35856992, end=35876084)
```
==========================================================================
And here is what I get:
![image](https://user-images.githubusercontent.com/41467037/75126119-78af0880-56f3-11ea-9658-f5e9cbb62a63.png)

Here is the code for the second method(standard method):
=========================================================================
```
ref_gen = genomeview.FastaGenomeSource('ucsc.hg19.fasta')
view = genomeview.GenomeView('chr5', 35856992, 35876084, "+", ref_gen)

pro_bam_track = genomeview.PairedEndBAMTrack("PID19-101.bqsr.bam", name="PID19-101_pro")
mo_bam_track = genomeview.PairedEndBAMTrack("PID19-102.bqsr.bam", name="PID19-102_mo")
fa_bam_track = genomeview.PairedEndBAMTrack("PID19-103.bqsr.bam", name="PID19-103_fa")

axis_track = genomeview.Axis()
view.add_track(axis_track)

gene_anno = genomeview.BEDTrack("refgene_genomeview_ready.sorted.bed", name='refGene')
view.add_track(gene_anno)

view.add_track(pro_bam_track)
view.add_track(axis_track)
view.add_track(gene_anno)
view.add_track(mo_bam_track)
view.add_track(axis_track)
view.add_track(gene_anno)
view.add_track(fa_bam_track)

doc = genomeview.Document(5000)
doc.add_view(view)

display(doc)
```
==========================================================================
And here is the result I get for the second part of my code:
![image](https://user-images.githubusercontent.com/41467037/75126238-f70baa80-56f3-11ea-86f7-3c113b02a29d.png)

I ran these codes in jupyter notebook. The screenshot are directly from jupyter notebook.

**Comment by nspies** [comment]
If I understand correctly, you've tried using the tabix method to load the bed file as well as the plain bed approach?

I'm not seeing anything obviously wrong in what you're trying to do. You're probably in the best place to try and debug this yourself -- to make sure the file is being parsed correctly, that the chromosome names and coordinates all line up, whether it's getting to the point of trying to display loci but failing...

If you want to send me your bed file, I can try to take a quick look, but no guarantees when that would be (possibly this week).

**Comment by nspies** [comment]
Also, it seems like it'd be better to display annotations from a gtf file, but I never got around to adding support for that ... happy to accept pull requests!

**Comment by ghost** [comment]
> If I understand correctly, you've tried using the tabix method to load the bed file as well as the plain bed approach?
> 
> I'm not seeing anything obviously wrong in what you're trying to do. You're probably in the best place to try and debug this yourself -- to make sure the file is being parsed correctly, that the chromosome names and coordinates all line up, whether it's getting to the point of trying to display loci but failing...
> 
> If you want to send me your bed file, I can try to take a quick look, but no guarantees when that would be (possibly this week).

Thank you for your quick response! 
I simply follow this part:
![image](https://user-images.githubusercontent.com/41467037/75126930-253eb980-56f7-11ea-9ddd-595638745b1c.png)
and this part:
![image](https://user-images.githubusercontent.com/41467037/75126949-3b4c7a00-56f7-11ea-9405-03e7902019f5.png)
in genomeview's official tutorial doc. I tried both of these two methods for my bed file. 

Here I attach my bed file to you. Since GitHub does not support the BED file type, I changed the suffix to TXT instead. Thank you so much for spending time inspecting this issue for me. 

[refgene_genomeview_ready.sorted.txt](https://github.com/nspies/genomeview/files/4243026/refgene_genomeview_ready.sorted.txt)

**Comment by ghost** [comment]
> Also, it seems like it'd be better to display annotations from a gtf file, but I never got around to adding support for that ... happy to accept pull requests!

Thanks for the heads up, I'll try to add annotation track using a gtf file, will let you hear as soon as I got it right!

**Comment by ghost** [comment]
> > Also, it seems like it'd be better to display annotations from a gtf file, but I never got around to adding support for that ... happy to accept pull requests!
> 
> Thanks for the heads up, I'll try to add annotation track using a gtf file, will let you hear as soon as I got it right!

Hmmm... I tried but for now, it seems difficult for me to customize a track and integrate the parsing code into genomeview. I think I'll just wait and see when is available for me to learn this.

**Comment by ghost** [comment]
> If I understand correctly, you've tried using the tabix method to load the bed file as well as the plain bed approach?
> 
> I'm not seeing anything obviously wrong in what you're trying to do. You're probably in the best place to try and debug this yourself -- to make sure the file is being parsed correctly, that the chromosome names and coordinates all line up, whether it's getting to the point of trying to display loci but failing...
> 
> If you want to send me your bed file, I can try to take a quick look, but no guarantees when that would be (possibly this week).

Dear @nspies @nspies-celsiustx , thanks for your time. I think I have solved this issue. After close inspection, I found that the last two columns of my bed file do not contain the same type of value as those in your example bed file. 

In your example bed file, the last two columns are exon length and exon relative starting sites. 
While in my bed file the last two columns are abs coordinates of exon starting sites and exon ending sites. 

Here I provide a summary of bed file format requirement for them to work in genomeview. And you can put it on your instruction doc:

#### The first three columns are chr, start, end
#### The fourth column should be the name
#### It does not provide field content of <font color='red'>the fifth column</font>.
#### The sixth column shoud be the strand
#### The seventh column should be cds_start
#### The eighth column should be cds_end
#### It does not provide field content of <font color='red'>the ninth column</font>.
#### The tenth column should be the total number of exons
#### The eleventh column should be the coordinates of length for every exon
#### The last column should be the relative coordinates of the starting site for every exon (the first one is always zero).

Again, thank you for your patience. I wish this post would find you well so you don't have to waste your time testing the bed file for me.

**Comment by nspies-celsiustx** [comment]
Glad you've figured it out!

For posterity, here's the precise definition of bed format that I was working from: 

https://genome.ucsc.edu/FAQ/FAQformat.html#format1

Obviously this is not a complete implementation, but I was at least going for compatibility with the ucsc formatted files.

**Comment by ghost** [comment]
> Glad you've figured it out!
> 
> For posterity, here's the precise definition of bed format that I was working from:
> 
> https://genome.ucsc.edu/FAQ/FAQformat.html#format1
> 
> Obviously this is not a complete implementation, but I was at least going for compatibility with the ucsc formatted files.

Ah... Thanks for the explanation.
One more thing, it would be great if we can put text regarding the gene name and exon number on the thick bars in the annotation track. But I find it hard to understand the Renderer class's argument "backend". When I specify it to a view object, it runs without an error but I can't see my text printed on the SVG pic. 

Anyway, this should not be a real problem, it's just some room for improvement. Thank you for taking time to look at this issue.

**Comment by nspies-celsiustx** [comment]
This line here is an example of how you would add some text: https://github.com/nspies/genomeview/blob/master/genomeview/bedtrack.py#L251

Sorry the renderer isn't better documented. The arguments to `Renderer.text` should be `x, y, label`, and you can use `self.scale.topixels` to convert genomic coordinates to screen coordinates.
